apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: xowldks1003/fastapi-app:49ff4d2fbfb08b532872a2daf5c5ace5b8f92a4f
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mysql-secret
