apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: xowldks1003/fastapi-app:ecbe51612f61b854c45226cd43772ba8c37cc681
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: mysql-secret
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100
