apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: xowldks1003/react-frontend:2377d8ee0afdde51f7bb3120d7a9d73d45afe54c
          ports:
            - containerPort: 80
