apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: xowldks1003/react-frontend:e2361fca7ffb6125f75bf8aa704c6f103c61ac72
          ports:
            - containerPort: 80
