name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./fastapi_back

      - run: |
          pip install flake8
          flake8 .
        working-directory: ./fastapi_back

      - run: docker build -t xowldks1003/fastapi-app:latest ./fastapi_back

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm install
        working-directory: ./react_front

      - run: npm run build
        working-directory: ./react_front

      - run: docker build -t xowldks1003/react-frontend:latest ./react_front

  push-images:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: docker push xowldks1003/fastapi-app:latest

      - run: docker push xowldks1003/react-frontend:latest

